apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookalbumbatch3
  name: bookalbumbatch3
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bookalbumbatch3
