apiVersion: apps/v1
kind: bookalbumbatch3
metadata:
  name: bookalbumbatch3
  labels:
    app: bookalbumbatch3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbumbatch3
  template:
    metadata:
      labels:
        app: bookalbumbatch3
    spec:
      containers:
      - name: bookalbumbatch3
        image: sreedocker123/bookmoviealbum:latest
        ports:
        - containerPort: 80
